//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STPGroup.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int ExperienceLevelId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime StartingDate { get; set; }
        public decimal Salary { get; set; }
        public int VacationDays { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual ExperienceLevels ExperienceLevels { get; set; }
    }
}
